src/components/alphabet-view/alphabet-view.tsx, src/components/alphabet-view/word-row-card.tsx, src/components/common/data/types.ts, src/components/common/full-screen-modal/full-screen-modal.tsx, src/components/dictionary-page/dictionary-page.tsx, src/components/songs-view/songs-view.tsx, src/components/temp-songs-list.tsx
Added in a temp list of songs.
Added in a type for the FVSong.
Format fixes.
Fixed an issue with the full screen modal.
=> Added in the songs view.

package-lock.json, package.json, src/components/common/data/types.ts, src/components/common/search-header/search-header.tsx, src/components/search-provider.tsx, src/components/temp-mtd-export-data.tsx, src/util/searchUtils.ts
Hey all, 
Here's a PR that replaces the old placeholder search with the new mothertongues search module we'll be using. I added the data from the new endpoint and replaced the search functionality that was there. I'm still just `console.log`'ing the results - hopefully this is enough to unblock you guys and let you continue! I tried to add comments throughout the changes that explained things, but feel free to remove my in-line comments as you see fit. As always feel free to ping me about any questions. The data format has changed slightly, and I updated the code to reflect those changes, but I'll put them in a different PR to help keep the changes interpretable.
=> feat: use @mothertongues/search package for search

src/components/stories-view/stories-view.tsx, src/services/apiService.ts
Added story icon for when there isn't an image on the list view for stories.
=> Updated the look of the stories view.

.github/workflows/fv-apps-deploy-dev.yml, .github/workflows/fv-apps-deploy-preprod.yml
Checklist
[] README / documentation has been updated if needed
[] PR title / commit messages contain Jira ticket number if applicable
[] Tests have been updated / created if applicable
[] Review the changes here
[] Pull the branch and test locally
N/A
=> Update deployment yamls to accomodate Dev

src/components/common/header/header.spec.tsx, src/components/common/header/header.tsx
added Link to homepage around logo in navbar
=> FW-5447-fv-logo-back-to-main

.github/workflows/fv-apps-deploy-dev.yml, .github/workflows/fv-apps-deploy-preprod.yml, .github/workflows/fv-apps-deploy-prod.yml
Checklist
[] README / documentation has been updated if needed
[] PR title / commit messages contain Jira ticket number if applicable
[] Tests have been updated / created if applicable
[] Review the changes here
[] Pull the branch and test locally
N/A
=> Merge main back to dev

.github/workflows/fv-apps-deploy-preprod.yml
Checklist
[] README / documentation has been updated if needed
[] PR title / commit messages contain Jira ticket number if applicable
[] Tests have been updated / created if applicable
[] Review the changes here
[] Pull the branch and test locally
N/A
=> Update workflow trigger on PR rules

.github/workflows/fv-apps-deploy-preprod.yml, __mocks__/axios.js, babel.config.js, config-overrides.js, package-lock.json, package.json, src/components/alphabet-view/alphabet-view.tsx, src/components/category-view/category-view.tsx, src/components/contexts/apiContext.tsx, src/components/dictionary-page/word-of-the-day.tsx, src/components/dictionary-view/dictionary-view.tsx, src/components/flashcards-view/flashcards-view.tsx, src/components/randomized-view/randomized-view.tsx, src/components/search-provider.tsx, src/index.tsx, src/services/wordsApiService.ts, src/testingUtils/renderWithProviders.tsx
Checklist
[] README / documentation has been updated if needed
[] PR title / commit messages contain Jira ticket number if applicable
[] Tests have been updated / created if applicable
[] Review the changes here
[] Pull the branch and test locally
N/A
=> Merge dev to main

.env, README.md, public/index.html
Changes:
* customize document title for each language, using info from the manifest
* updated document description with a static summary
* minor readme updates
Checklist
- Tests have been updated / created if applicable
N/A
=> fw-5777, updated title and description

.env, src/components/common/convert-json/convert-json.tsx, src/components/songs-view/songs-view.tsx, src/components/stories-view/stories-view.tsx
- Lyrics were actually displayed correctly, but many songs in the FirstVoices data have the lyrics in the introduction field.
- This adds the song introduction and introductionTranslation to the song detail screen
Checklist
- README / documentation has been updated if needed
- Tests have been updated / created if applicable
N/A
=> Fw-5510, fix for missing song lyrics

src/components/common/data/type-guards.ts, src/components/dictionary-view/dictionary-view.tsx
- fixed issue in type-guard for FvWordLocationCombo that was resulting in blank word cards 
Checklist
N/A
=> FW-5821 search tabs

src/components/dictionary-page/word-modal.tsx, src/components/songs-view/songs-view.tsx, src/components/stories-view/stories-view.tsx
-hid share button on words, stories, songs
Checklist
N/A
=> FW-5780-hide-share-button

src/assets/variables.css, src/components/alphabet-view/alphabet-view.tsx, src/components/alphabet-view/download-button.tsx, src/components/alphabet-view/keyboard.tsx, src/components/alphabet-view/selected-letter-display.tsx, src/components/alphabet-view/word-example-list.tsx, src/components/alphabet-view/word-starts-with-list.tsx, src/components/categories-view/categories-view.tsx, src/components/dictionary-page/dictionary-page.tsx, src/components/dictionary-page/word-card-mobile.tsx, src/components/dictionary-page/word-card.tsx, src/components/learn/learn.tsx, src/components/sub-nav-mobile/sub-nav-mobile.tsx, src/index.tsx
- Refactored the Alphabet page to reduce lag and load times when navigating between letters.
- Changed mobile view by removing split/separating alphabet functionality - now showing all character details in full screen modal on character click/tap
- Also reduced cognitive load of alphabet-view by breaking it down into smaller components
Checklist
N/A
=> FW-5787 alphabet selected close lag

src/components/profile-view/profile-view.tsx
- edited text for clarity
Checklist
N/A
=> FW-5795-unbookmark-to-edit-bookmark

package-lock.json, package.json, src/components/alphabet-view/alphabet-view.tsx, src/components/common/page-not-found/page-not-found.tsx
- fix eslint warning for alphabet-view
- replace single use of Lodash in page-not-found and fix “Contact support” link
- remove Lodash dependency
Checklist
N/A
=> FW-5829 remove lodash

public/index.html
- removing backup/hard-coded link for apple-touch-icon and favicon 
Checklist
N/A
=> FW-5740 Remove hardcoded icon links

src/components/alphabet-view/download-button.tsx, src/service-worker.ts, src/services/indexedDbService.ts
- 100% pure console logs
Checklist
N/A
=> Fw-5784, temporary debug logging related to caching and media downloads

src/components/alphabet-view/download-button.tsx, src/service-worker.ts, src/services/indexedDbService.ts
- console logs again
Checklist
N/A
=> Fw-5784, more service worker logging

src/service-worker.ts
- Possible fix for caching failures and images failing to load
Checklist
N/A
=> fw-5784, prevent default fetching

src/components/common/deletable-list/deletable-list.spec.tsx, src/components/common/deletable-list/deletable-list.stories.tsx, src/components/common/deletable-list/deletable-list.tsx, src/components/profile-view/profile-view.tsx, tailwind.config.js
- matched colors and styling of type badge
- adjusted spacing and alignment of bookmark items on mobile and tablet
- allowed for longer text
- matched colors of edit buttons and shading to FV color palette
- reduced size of Bookmark title on tablet
- hid bookmark title on mobile to allow space for edit buttons
- added color indicator of type in mobile view
- removed unused search from deletable-list
Checklist
N/A
=> FW-5514 Adjust bookmark styling

src/components/common/audio-button/audio.tsx, src/components/common/audio-control/audio-control.tsx, src/service-worker.ts
- eliminate duplicate requests in the service worker
- update audio button to avoid serving from cache when online
- some additional logging for verifying the songs and stories audio
Checklist
N/A
=> Fw-5848, improved audio caching

src/service-worker.ts
- fixes audio requests when caching is enabled (aka in production)
Checklist
N/A
=> fw-5848, avoid reading response twice

src/service-worker.ts
- skip caching for failed/aborted requests
Checklist
N/A
=> fw-5848, don't cache failed requests

src/components/common/audio-button/audio.tsx, src/service-worker.ts
- just console logs
Checklist
N/A
=> fw-5848, additional logging

src/service-worker.ts
- don't treat requests served from the browser cache as errors
Checklist
N/A
=> Fw 5848 audio cache

src/service-worker.ts
- always serve from cache if available
Checklist
N/A
=> fw-5848, adjust caching to assume immutable media files

src/service-worker.ts, src/services/indexedDbService.ts
- handle situation where two file requests are made concurrently and one is cached first
- handle situation where a non-error response does not contain a valid file
Checklist
N/A
=> Fw-5848, error handling in caching

src/components/common/audio-button/audio.tsx, src/components/common/audio-control/audio-control.tsx, src/service-worker.ts, src/services/indexedDbService.ts
=> fw-5848, remove some logs

src/services/indexedDbService.ts
- only update last access date for non-null records
Checklist
N/A
=> fw-5848, eliminate blank cached items

src/service-worker.ts
=> fw-5848, use cors mode to fetch media files

src/components/common/audio-button/audio.tsx
=> fw-5848, reduce duplicate audio requests

src/service-worker.ts
=> fw-5862, removing noisy logs

src/components/common/mobile-nav/mobile-nav.spec.tsx
- updates test to allow for the addition of useLocation inside MobileNav
Checklist
N/A
=> Ensure test is run inside BrowserRouter

src/components/alphabet-view/download-button.tsx
=> fw-5800, more detailed message when bulk downloading media

src/components/common/multi-switch/multi-switch.module.css, src/components/common/multi-switch/multi-switch.tsx, src/components/song-page/song-page.tsx, src/components/song-view/song-view.module.css, src/components/song-view/song-view.tsx, src/components/songs-page/songs-page.tsx, src/components/songs-view/songs-view.tsx, src/components/stories-view/stories-view.tsx, src/components/story-view/cover-view.tsx, src/components/story-view/story-view.tsx, src/components/sub-nav-desktop/sub-nav-desktop.tsx, src/index.tsx
- updated Songs to have dedicated song route - songs/:id
- adjusted multi-switch styling
- update story bookmark url to use direct route (not hash)
- adjustments to styling of song and story pages for consistency
Checklist
N/A
=> FW-5868 dictionary bookmarks, song bookmarks

src/services/indexedDbService.ts
- move the buffer -> blob conversion inside a condition, to avoid errors on missing files
Checklist
N/A
=> fw-5884, update to handle missing files in cache

src/services/indexedDbService.ts
=> fw-5884, yet more logging in the media cache

src/service-worker.ts, src/services/indexedDbService.ts
=> Fw 5884, more logging for file types in the media cache

src/services/indexedDbService.ts
=> Fw-5884, add logging about potential errors with store.add

src/services/indexedDbService.ts
- avoid returning control to the event loop before finishing all store operations, aka don't await anything in between creating the store and using it
Checklist
N/A
=> fw-5884, fix for transaction closing before caching media

src/components/alphabet-view/alphabet-view.tsx, src/components/alphabet-view/download-button.tsx, src/components/alphabet-view/keyboard.tsx, src/components/alphabet-view/selected-letter-display.tsx, src/components/alphabet-view/word-example-list.tsx, src/components/alphabet-view/word-starts-with-list.tsx, src/components/common/data/type-guards.ts, src/components/common/data/types.ts, src/services/charactersApiService.ts, src/util/useStartsWithChar.ts
- Implement smart filtering for getting entries that start with a character in Alphabet view and download
- rename type FvLetter to FvCharacter
- remove final reference to type FvWordLocationCombo
Checklist
N/A
=> FW-5906 smart starts with char

src/components/common/audio-button/audio.tsx
=> fw-5884, logging for ff cache issue

src/service-worker.ts
=> FW-6005 Only count 200 as NotFailed

src/components/common/alert/alert.module.css, src/components/common/alert/alert.tsx, src/components/flashcards-view/flashcard-view.tsx, src/components/flashcards-view/flashcards-view.module.css, src/index.css
- Fix flashcard flipping issue for iOS prior to 17
- Make Alert dismiss on click outside and raise from bottom to ensure it is not covered by nav in mobile view
Checklist
N/A
=> FW-5939 flashcard flip ios

public/index.html, src/components/about-view/about-view.tsx, src/serviceWorkerRegistration.ts, webpack.config.js
- Updated server to serve on dev from `https` to `http`.
- Fixed relative paths for different assets.
Checklist
- ~README / documentation has been updated if needed~
- ~Tests have been updated / created if applicable~
N/A
=> FW-5830 Relative path and service worker fixes

src/components/common/multi-switch/multi-switch.tsx
added conditional styling to icon
N/A
=> FW-6117-word/phrase-toggle-icon

public/index.html
Please briefly explain the changes here.
N/A
=> FW-6193 added matomo analytics

src/components/flashcards-view/flashcards-view.tsx
- Removed the source type matching on bookmarks filtering since we are already matching IDs.
- ~Tests have been updated / created if applicable~
N/A
=> FW-6233 Removed source type checking in flashcards view bookmakrs tab

src/components/dictionary-view/word-modal.tsx
(Entity (Noun-like word)) to Entity (Noun-like word)
Removes parenthesis from the word
N/A
=> FW-6058 parenthesis fix

public/index.html, src/components/about-view/about-view.tsx, src/components/common/convert-json/convert-json.tsx, webpack.config.js
- Fixed conditional rendering for chrome, and moved manifest files out of assets folder
N/A
=> FW-6408 Conditional rendering fix for chrome

package-lock.json, package.json
Upgrade axios package to address CVE-2025-27152
Please briefly explain the changes here.
N/A
=> Fix vulnerability CVE-2025-27152 with axios upgrade

src/components/flashcards-view/flashcard-view.tsx, src/components/flashcards-view/flashcards-view.tsx
flashcards would appear empty because...
Text would randomly get tagged as audio so text will NOT appear.
N/A
=> FW-6545 - Empty Flashcard should now appear

src/components/common/modal/modal.tsx, src/components/contexts/installPromptContext.tsx, src/components/dictionary-page/word-of-the-day.tsx, src/components/install-prompt/install-prompt.tsx
Fixed closing wotd and install prompt to close at the same time
N/A
=> FW-6702 Fixed WOTD and Install Prompt closing at the same time.

src/service-worker.ts
Refactored fetch method in service-worker to allow js files to be passed to service-worker to handle caching
Please briefly explain the changes here.
N/A
=> FW-6769 Fix cors mode for analytics server
